name: cicd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./weather

      - name: Build
        run: npm run build
        working-directory: ./weather
        env:
          CI: false

      - name: Deploy on GH-Pages
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://korenezri.github.io/Koren-BenEzri-19.09.2021/#/
          npm run deploy
        env:
          user_name: "KorenEzri"
          user_email: "korenatdevelopes@gmail.com"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          CI: false
        working-directory: ./weather
